version: "2"                        --docker-compose的版本
services:
  resume1.0:
    image: node:latest
    working_dir: "/home"
    environment:
      - HOST=0.0.0.0
    ports:
      - "3003:8989"                 --暴露的端口：项目中的端口
    volumes:
      - ./home:/home
    command: bash -c "npm run start"
