version: "2"
services:
  resume1.0:
    image: node:latest
    working_dir: "/bilibili"
    environment:
      - HOST=0.0.0.0
    ports:
      - "3003:8989"
    volumes:
      - ./bilibili:/bilibili
    command: bash -c "yarn start"
